### ISSUE TITLE
Is there anyway to execute the eval-APH.py without matlab?

### ISSUE THREAD

**Issue by wingwingyang** [zhou13/lcnn#39]
Thanks for your sharing first. It is inconvenient for me to install the matlab on Ubuntu ,and we do not have the license of MATLAB so that will bring us some trouble. So I want to ask that if there is anyway to get the APH value without matlab.

I am also confused that what the difference between the "wireframe_raw.rar" and "wireframe.rar" is in details. I did not find the relevant code or instruction.

**Comment by zhou13** [comment]
Regarding MATLAB dependency, you could try to rewrite it in Python since the source code is given. It might take you some time but that would be a good contribution to the community!

`wireframe_raw.tar` is the original dataset from ShanghaiTech. `wireframe.rar` is the data with our processing. See the section "Processing the Dataset" for details.

**Comment by wingwingyang** [comment]
Can you give me the correspondPixel.mexw64 please? Because there is no C source code, I cannot excute this file. Now I want to try to run `eval_release.m` on Windows.

**Comment by zhou13** [comment]
Could you check if https://github.com/pdollar/edges/blob/master/private/correspondPixels.mexw64 works for you? This should come from an ancient Matlab code.

**Comment by wingwingyang** [comment]
Thank you very much! It works.
