### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by zhangfuyang** [zhou13/lcnn#8]
Hi,

I am trying to reproduce the result. I am using the same gpu as the paper said (1080 ti, with 11G memory). 
When I run the train.py, everything is fine at beginning, but once run into validate method in trainer.py, there will be out of memory error after few running steps. It looks like some data isn't released and memory keep growing. I change batch size to 4 still meet  this problem.

The only thing I modified is in line 197, line_vectorizer.py. Change 'c = torch.zeros_like(label)' -> 'c = torch.zeros_like(label).bool()', because it keeps printing the warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.

Could you please help me check out the problem? Also, could you please tell me what's version of pytorch as well as other packages you are using? Even though I don't think it is caused by torch version, but I feel it would be better if I can run the code in the total same environment.

Thank you!

**Comment by zhou13** [comment]
Thank you for reporting the problem. I think the problem was introduced in the fix of #5. It might not be related to PyTorch. I add the commits to reduce memory usage and fix the warning you mentioned but I do not have enough resources to test it right now. Let me know if that fixes your problem. If not, try to reduce the value of `eval_junc_thres` in `config/wireframe.yaml`, though it might have small negative impact on the metrics (only with the evaluation during training).

**Comment by zhou13** [comment]
Another option is to use 4c741161 for training and master for testing until I fix the problem.

**Comment by zhangfuyang** [comment]
The current branch is good now. Thank you!

**Comment by zhou13** [comment]
@zhangfuyang @xiapengchng  I reduce the evaluation batch_size so the model should train without modification of the default yaml. Let me know if the problem persists.
